name: 'cargo-semver-checks'
description: 'Ensure the public API in your Rust crate follows semantic versioning'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  package:
    description: 'The package whose API to check for semver (in Package Id Specification format, see https://doc.rust-lang.org/cargo/reference/pkgid-spec.html for reference). If not set, all packages defined in the Cargo.toml file are processed.'
    required: false
  manifest-path:
    description: 'Path to Cargo.toml of crate or workspace to check. If not specified, the action assumes the manifest is under the default `GITHUB_WORKSPACE` path.'
    required: false
  verbose:
    description: 'Enables verbose output of `cargo-semver-checks`.'
    type: boolean
    required: true
    default: false
  cache-key:
    description: 'Rustdoc baseline is cached separately for runs that differ in at least one of the following: runner OS, `rustc` version, `cargo-semver-checks` version, or any of the `Cargo.lock` files in the current workspace. This input might be used to further separate the caches by providing the unique key (by default the job name) for each of them.'
    required: false
    default: ${{ github.job }}
  prefix-key:
    description: 'Additional prefix of the cache key, can be set to start a new cache manually.'
    required: false
  github-token:
    description: 'The `GITHUB_TOKEN` secret used to download precompiled binaries from GitHub API. If not specified, the automatic GitHub token provided to the workflow will be used.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
