name: 'cargo-semver-checks'
description: 'Ensure the public API in your Rust crate follows semantic versioning'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  package:
    description: 'Comma-separated list of the packages whose API to check for semver (in Package Id Specification format, see https://doc.rust-lang.org/cargo/reference/pkgid-spec.html for reference). If not set, all packages defined in the Cargo.toml file are processed.'
    required: false
  exclude:
    description: 'Comma-separated list of the packages that will be excluded from being processed. Has effect only if the input `package` is not specified.'
    required: false
  manifest-path:
    description: 'Path to Cargo.toml of crate or workspace to check. If not specified, the action assumes the manifest is under the default `GITHUB_WORKSPACE` path.'
    required: false
  feature-group:
    description: 'Override the feature group used for semver-checking, for example if you only want to check with default features.'
    required: false
  features:
    description: 'Comma-separated list of crate features to explicitly include when semver-checking.'
    required: false
  verbose:
    description: 'Enables verbose output of `cargo-semver-checks`.'
    required: true
    default: 'false'
  release-type:
    description: 'Sets the release type instead of deriving it from the version number specified in the `Cargo.toml` file.'
    required: false
  rust-toolchain:
    description: 'Rust toolchain name to use, e.g. `stable`, `nightly` or `1.68.0`. It will be installed if necessary and used regardless of local overrides and the `rust-toolchain.toml` file. However, if the input is set to `manual`, the action assumes some Rust toolchain is already installed and uses the default one.'
    default: 'stable'
  shared-key:
    description: 'A cache key that will be used instead of the automatic key based on the name of the GitHub job and values of the inputs `package`, `exclude` and `manifest-path`. Might be provided e.g. to share the cache between the jobs.'
    required: false
    default: ''
  prefix-key:
    description: 'Additional prefix of the cache key, can be set to start a new cache manually.'
    required: false
  github-token:
    description: 'The `GITHUB_TOKEN` secret used to download precompiled binaries from GitHub API. If not specified, the automatic GitHub token provided to the workflow will be used.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
