name: Setup test workspace
inputs:
  ref-slice-ref:
    description: 'Reference of the ref_slice to checkout'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
      - name: Checkout the ref-slice fork
        uses: actions/checkout@v3
        with:
          repository: mgr0dzicki/cargo-semver-action-ref-slice
          ref: ${{ inputs.ref-slice-ref }}
          persist-credentials: true
          path: ref_slice
      - name: Create dummy crate
        # This crate does not have a matching baseline on crates.io, so any try
        # of checking it should make cargo-semver-checks fail.
        run: cargo new cargo-semver-action-dummy --lib
        shell: bash
      - name: Create workspace Cargo.toml
        run: echo -e "[workspace]\nmembers=['ref_slice','cargo-semver-action-dummy']" > Cargo.toml
        shell: bash
